# Generated by Django 4.1.3 on 2023-02-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gander',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
