# Generated by Django 4.1.3 on 2023-02-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boos', '0002_employee_gander_employee_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('start_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
