# Generated by Django 4.1.3 on 2023-02-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boos', '0008_rename_postion_employee_job_remove_job_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='project',
            field=models.ManyToManyField(null=True, to='boos.project'),
        ),
    ]
