# Generated by Django 4.1.3 on 2023-02-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boos', '0014_alter_employee_gander_alter_employee_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gander',
            field=models.IntegerField(choices=[(1, 'male'), (2, 'female')], max_length=200, null=True),
        ),
    ]
