# Generated by Django 4.1.3 on 2023-02-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boos', '0015_alter_employee_gander'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gander',
            field=models.IntegerField(choices=[(1, 'male'), (0, 'female')], null=True),
        ),
    ]
